"""Collect the real numbers from out\\*\\report.json (and detection / human-notes scores)
into out\\METRICS_SUMMARY.md. Every number in the docs should come from this file.

    python scripts\\summarize_runs.py
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "out"


def _load(p: Path) -> dict | None:
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def _checks(rep: dict) -> str:
    return "\n".join(f"| {c['name']} | {c['status']}{' (blocking)' if c['blocking'] else ''} | {c['detail']} |"
                     for c in rep["checks"])


def main() -> None:
    lines = ["# Nazeer: metrics from the demo runs", "",
             "Generated by `python scripts\\summarize_runs.py` from the report files in `out\\`.",
             "Demo data is generated (no real people). Detection numbers on generated data show that the",
             "planted formats are covered; they do not predict performance on real production text.", ""]
    det = _load(OUT / "detection_scores.json")
    if det:
        lines += ["## Free-text detection on the demo answer key", "",
                  "| identifier | planted | Nazeer recall | Nazeer precision | baseline recall | baseline precision |",
                  "|---|---|---|---|---|---|"]
        for t in ("SAUDI_ID", "MOBILE", "IBAN", "EMAIL", "PERSON_NAME"):
            n, b = det["nazeer"]["per_type"][t], det["baseline"]["per_type"][t]
            f = lambda v: "–" if v is None else f"{v:.3f}"  # noqa: E731
            lines.append(f"| {t} | {n['golden']:,} | {f(n['recall'])} | {f(n['precision'])} | {f(b['recall'])} | {f(b['precision'])} |")
        n, b = det["nazeer"], det["baseline"]
        lines += [f"| **overall** | {sum(v['golden'] for v in n['per_type'].values()):,} | **{n['overall_recall']:.3f}** | "
                  f"**{n['overall_precision']:.3f}** | **{b['overall_recall']:.3f}** | **{b['overall_precision']:.3f}** |", "",
                  f"Look-alike numbers and name-like words wrongly flagged: Nazeer {n['hard_negative_hits']} of "
                  f"{n['hard_negatives']:,}, baseline {b['hard_negative_hits']} of {b['hard_negatives']:,}.", ""]
    for name, title in (("masked_no_fix", "Masked twin (no k-anonymity fix applied)"),
                        ("masked", "Masked twin (best k-anonymity fix applied)"),
                        ("synthetic", "Synthetic twin"),
                        ("mysql_masked", "MySQL: production database → masked twin → development database")):
        rep = _load(OUT / name / "report.json")
        if not rep:
            continue
        lines += [f"## {title}", "", f"Run `{rep['run_id']}` · verdict **{rep['verdict']}**", "",
                  "| check | status | detail |", "|---|---|---|", _checks(rep), ""]
    human = _load(OUT / "human_eval.json")
    lines += ["## Hand-written notes (independent evaluation)", ""]
    if human:
        n, b = human["nazeer"], human["baseline"]
        lines += [f"{human['notes']} notes, {sum(human['golden_by_type'].values())} marked identifiers, name detector "
                  f"`{human.get('name_detector')}`. Nazeer recall {n['overall_recall']}, precision {n['overall_precision']}; "
                  f"baseline recall {b['overall_recall']}, precision {b['overall_precision']}.", ""]
    else:
        lines += ["Not available yet: `data\\human_notes.csv` has not been written.", ""]
    (OUT / "METRICS_SUMMARY.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"written: {OUT / 'METRICS_SUMMARY.md'}")


if __name__ == "__main__":
    main()
